"""add_unique_imei

Revision ID: 2fb605563781
Revises: dd46bfd70d1b
Create Date: 2026-02-26 12:25:03.321582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2fb605563781'
down_revision: Union[str, Sequence[str], None] = 'dd46bfd70d1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personal_assets_imei_1'), table_name='personal_assets')
    op.drop_index(op.f('ix_personal_assets_owner_id'), table_name='personal_assets')
    op.drop_index(op.f('ix_personal_assets_serial_number'), table_name='personal_assets')
    op.drop_table('personal_assets')
    op.drop_column('equipment', 'seal_check_date')
    op.drop_column('equipment', 'seal_number')
    op.drop_column('equipment', 'seal_install_date')
    op.drop_column('equipment', 'seal_status')
    op.drop_column('equipment_movements', 'seal_number_after')
    op.drop_column('equipment_movements', 'seal_number_before')
    op.drop_column('equipment_movements', 'seal_status')
    op.create_unique_constraint('uq_phone_imei_1', 'phones', ['imei_1'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_phone_imei_1', 'phones', type_='unique')
    op.add_column('equipment_movements', sa.Column('seal_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('equipment_movements', sa.Column('seal_number_before', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('equipment_movements', sa.Column('seal_number_after', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('equipment', sa.Column('seal_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('equipment', sa.Column('seal_install_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('equipment', sa.Column('seal_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('equipment', sa.Column('seal_check_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_table('personal_assets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('asset_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('serial_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('imei_1', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('imei_2', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('has_camera', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('has_recorder', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('has_charger', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('charger_functional', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('storage_location', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'checked_out'::character varying"), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("asset_type::text = ANY (ARRAY['phone'::character varying, 'laptop'::character varying]::text[])", name=op.f('ck_personal_asset_type')),
    sa.CheckConstraint("status::text = ANY (ARRAY['checked_in'::character varying, 'checked_out'::character varying]::text[])", name=op.f('ck_personal_asset_status')),
    sa.ForeignKeyConstraint(['owner_id'], ['personnel.id'], name=op.f('personal_assets_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('personal_assets_pkey'))
    )
    op.create_index(op.f('ix_personal_assets_serial_number'), 'personal_assets', ['serial_number'], unique=False)
    op.create_index(op.f('ix_personal_assets_owner_id'), 'personal_assets', ['owner_id'], unique=False)
    op.create_index(op.f('ix_personal_assets_imei_1'), 'personal_assets', ['imei_1'], unique=False)
    # ### end Alembic commands ###
