"""Add equipment tables

Revision ID: 655a1551ed54
Revises: d1585aca1722
Create Date: 2026-02-07 18:20:11.358088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '655a1551ed54'
down_revision: Union[str, Sequence[str], None] = 'd1585aca1722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_type', sa.String(length=50), nullable=False),
    sa.Column('inventory_number', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('cpu', sa.String(length=255), nullable=True),
    sa.Column('ram_gb', sa.Integer(), nullable=True),
    sa.Column('storage_type', sa.String(length=50), nullable=True),
    sa.Column('storage_capacity_gb', sa.Integer(), nullable=True),
    sa.Column('has_optical_drive', sa.Boolean(), nullable=True),
    sa.Column('has_card_reader', sa.Boolean(), nullable=True),
    sa.Column('operating_system', sa.String(length=100), nullable=True),
    sa.Column('current_owner_id', sa.Integer(), nullable=True),
    sa.Column('current_location', sa.String(length=255), nullable=True),
    sa.Column('seal_number', sa.String(length=100), nullable=True),
    sa.Column('seal_install_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seal_status', sa.String(length=50), nullable=True),
    sa.Column('seal_check_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['current_owner_id'], ['personnel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_id'), 'equipment', ['id'], unique=False)
    op.create_index(op.f('ix_equipment_inventory_number'), 'equipment', ['inventory_number'], unique=True)
    op.create_index(op.f('ix_equipment_serial_number'), 'equipment', ['serial_number'], unique=False)
    op.create_table('equipment_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('from_location', sa.String(length=255), nullable=True),
    sa.Column('to_location', sa.String(length=255), nullable=True),
    sa.Column('from_person_id', sa.Integer(), nullable=True),
    sa.Column('to_person_id', sa.Integer(), nullable=True),
    sa.Column('movement_type', sa.String(length=50), nullable=True),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('document_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('seal_number_before', sa.String(length=100), nullable=True),
    sa.Column('seal_number_after', sa.String(length=100), nullable=True),
    sa.Column('seal_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_person_id'], ['personnel.id'], ),
    sa.ForeignKeyConstraint(['to_person_id'], ['personnel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_movements_id'), 'equipment_movements', ['id'], unique=False)
    op.create_table('storage_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('inventory_number', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('capacity_gb', sa.Integer(), nullable=True),
    sa.Column('interface', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_devices_id'), 'storage_devices', ['id'], unique=False)
    op.create_index(op.f('ix_storage_devices_inventory_number'), 'storage_devices', ['inventory_number'], unique=True)
    op.create_index(op.f('ix_storage_devices_serial_number'), 'storage_devices', ['serial_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_storage_devices_serial_number'), table_name='storage_devices')
    op.drop_index(op.f('ix_storage_devices_inventory_number'), table_name='storage_devices')
    op.drop_index(op.f('ix_storage_devices_id'), table_name='storage_devices')
    op.drop_table('storage_devices')
    op.drop_index(op.f('ix_equipment_movements_id'), table_name='equipment_movements')
    op.drop_table('equipment_movements')
    op.drop_index(op.f('ix_equipment_serial_number'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_inventory_number'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_id'), table_name='equipment')
    op.drop_table('equipment')
    # ### end Alembic commands ###
