"""Create phones table

Revision ID: 9e3397ded709
Revises: 85a672ce1c33
Create Date: 2026-02-07 10:03:15.447603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e3397ded709'
down_revision: Union[str, Sequence[str], None] = '85a672ce1c33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phones_owner_id'), table_name='phones')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_phones_owner_id'), 'phones', ['owner_id'], unique=False)
    # ### end Alembic commands ###
