"""Initial migration

Revision ID: b334d448cabe
Revises: 
Create Date: 2026-02-08 18:05:02.329879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b334d448cabe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personnel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('rank', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=100), nullable=True),
    sa.Column('personal_number', sa.String(length=50), nullable=True),
    sa.Column('service_number', sa.String(length=50), nullable=True),
    sa.Column('security_clearance_level', sa.Integer(), nullable=True),
    sa.Column('clearance_order_number', sa.String(length=100), nullable=True),
    sa.Column('clearance_expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('personal_number')
    )
    op.create_index(op.f('ix_personnel_full_name'), 'personnel', ['full_name'], unique=False)
    op.create_index(op.f('ix_personnel_id'), 'personnel', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_type', sa.String(length=50), nullable=False),
    sa.Column('inventory_number', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('mni_serial_number', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('cpu', sa.String(length=255), nullable=True),
    sa.Column('ram_gb', sa.Integer(), nullable=True),
    sa.Column('storage_type', sa.String(length=50), nullable=True),
    sa.Column('storage_capacity_gb', sa.Integer(), nullable=True),
    sa.Column('has_optical_drive', sa.Boolean(), nullable=True),
    sa.Column('has_card_reader', sa.Boolean(), nullable=True),
    sa.Column('operating_system', sa.String(length=100), nullable=True),
    sa.Column('current_owner_id', sa.Integer(), nullable=True),
    sa.Column('current_location', sa.String(length=255), nullable=True),
    sa.Column('seal_number', sa.String(length=100), nullable=True),
    sa.Column('seal_install_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seal_status', sa.String(length=50), nullable=True),
    sa.Column('seal_check_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['current_owner_id'], ['personnel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_id'), 'equipment', ['id'], unique=False)
    op.create_index(op.f('ix_equipment_inventory_number'), 'equipment', ['inventory_number'], unique=True)
    op.create_index(op.f('ix_equipment_mni_serial_number'), 'equipment', ['mni_serial_number'], unique=False)
    op.create_index(op.f('ix_equipment_serial_number'), 'equipment', ['serial_number'], unique=False)
    op.create_table('phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('imei_1', sa.String(length=15), nullable=True),
    sa.Column('imei_2', sa.String(length=15), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('has_camera', sa.Boolean(), nullable=True),
    sa.Column('has_recorder', sa.Boolean(), nullable=True),
    sa.Column('storage_location', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['personnel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phones_id'), 'phones', ['id'], unique=False)
    op.create_index(op.f('ix_phones_imei_1'), 'phones', ['imei_1'], unique=False)
    op.create_table('equipment_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('from_location', sa.String(length=255), nullable=True),
    sa.Column('to_location', sa.String(length=255), nullable=True),
    sa.Column('from_person_id', sa.Integer(), nullable=True),
    sa.Column('to_person_id', sa.Integer(), nullable=True),
    sa.Column('movement_type', sa.String(length=50), nullable=True),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('document_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('seal_number_before', sa.String(length=100), nullable=True),
    sa.Column('seal_number_after', sa.String(length=100), nullable=True),
    sa.Column('seal_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_person_id'], ['personnel.id'], ),
    sa.ForeignKeyConstraint(['to_person_id'], ['personnel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_movements_id'), 'equipment_movements', ['id'], unique=False)
    op.create_table('storage_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('inventory_number', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('capacity_gb', sa.Integer(), nullable=True),
    sa.Column('interface', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_devices_id'), 'storage_devices', ['id'], unique=False)
    op.create_index(op.f('ix_storage_devices_inventory_number'), 'storage_devices', ['inventory_number'], unique=True)
    op.create_index(op.f('ix_storage_devices_serial_number'), 'storage_devices', ['serial_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_storage_devices_serial_number'), table_name='storage_devices')
    op.drop_index(op.f('ix_storage_devices_inventory_number'), table_name='storage_devices')
    op.drop_index(op.f('ix_storage_devices_id'), table_name='storage_devices')
    op.drop_table('storage_devices')
    op.drop_index(op.f('ix_equipment_movements_id'), table_name='equipment_movements')
    op.drop_table('equipment_movements')
    op.drop_index(op.f('ix_phones_imei_1'), table_name='phones')
    op.drop_index(op.f('ix_phones_id'), table_name='phones')
    op.drop_table('phones')
    op.drop_index(op.f('ix_equipment_serial_number'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_mni_serial_number'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_inventory_number'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_id'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_personnel_id'), table_name='personnel')
    op.drop_index(op.f('ix_personnel_full_name'), table_name='personnel')
    op.drop_table('personnel')
    # ### end Alembic commands ###
