"""Create personnel table

Revision ID: b6f0493c9a10
Revises: 39b09d2b434a
Create Date: 2026-02-07 08:14:06.756823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6f0493c9a10'
down_revision: Union[str, Sequence[str], None] = '39b09d2b434a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personnel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('rank', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=100), nullable=True),
    sa.Column('personal_number', sa.String(length=50), nullable=True),
    sa.Column('service_number', sa.String(length=50), nullable=True),
    sa.Column('security_clearance_level', sa.Integer(), nullable=True),
    sa.Column('clearance_order_number', sa.String(length=100), nullable=True),
    sa.Column('clearance_expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('personal_number')
    )
    op.create_index(op.f('ix_personnel_full_name'), 'personnel', ['full_name'], unique=False)
    op.create_index(op.f('ix_personnel_id'), 'personnel', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personnel_id'), table_name='personnel')
    op.drop_index(op.f('ix_personnel_full_name'), table_name='personnel')
    op.drop_table('personnel')
    # ### end Alembic commands ###
