"""Create phones table

Revision ID: d1585aca1722
Revises: b6f0493c9a10
Create Date: 2026-02-07 09:51:48.423683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1585aca1722'
down_revision: Union[str, Sequence[str], None] = 'b6f0493c9a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('imei_1', sa.String(length=15), nullable=True),
    sa.Column('imei_2', sa.String(length=15), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('has_camera', sa.Boolean(), nullable=True),
    sa.Column('has_recorder', sa.Boolean(), nullable=True),
    sa.Column('storage_location', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['personnel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phones_id'), 'phones', ['id'], unique=False)
    op.create_index(op.f('ix_phones_imei_1'), 'phones', ['imei_1'], unique=False)
    op.create_index(op.f('ix_phones_owner_id'), 'phones', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phones_owner_id'), table_name='phones')
    op.drop_index(op.f('ix_phones_imei_1'), table_name='phones')
    op.drop_index(op.f('ix_phones_id'), table_name='phones')
    op.drop_table('phones')
    # ### end Alembic commands ###
